name: brush_strokes
description: BrushStrokes is a painting shop and auction platform that allows users to browse and bid on a wide range of artwork

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  envied: ^0.3.0
  equatable: ^2.0.5

  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_spinkit: ^5.1.0

  google_fonts: ^4.0.3
  http: ^0.13.4
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  json_annotation: ^4.8.0
  shimmer: ^2.0.0
  shrine_images: ^2.0.2


dev_dependencies:
  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  flutter_launcher_icons: ^0.12.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  very_good_analysis: ^4.0.0+1

flutter_icons:
  android: "launcher_icon"
  ios: true
  min_sdk_android: 21
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
