name: brush_strokes
description: BrushStrokes is a painting shop and auction platform that allows users to browse and bid on a wide range of artwork

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_spinkit: ^5.1.0
  intl: ^0.18.0
  http: ^0.13.4
  cached_network_image: ^3.2.3
  internet_connection_checker: ^1.0.0+1
  equatable: ^2.0.5
  cupertino_icons: ^1.0.2
  shrine_images: ^2.0.1
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_launcher_icons: ^0.12.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  min_sdk_android: 21
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
